require=function(r,e,n){function t(n,o){function i(r){return t(i.resolve(r))}function f(e){return r[n][1][e]||e}if(!e[n]){if(!r[n]){var c="function"==typeof require&&require;if(!o&&c)return c(n,!0);if(u)return u(n,!0);var l=new Error("Cannot find module '"+n+"'");throw l.code="MODULE_NOT_FOUND",l}i.resolve=f;var a=e[n]=new t.Module;r[n][0].call(a.exports,i,a,a.exports)}return e[n].exports}function o(){this.bundle=t,this.exports={}}var u="function"==typeof require&&require;t.Module=o,t.modules=r,t.cache=e,t.parent=u;for(var i=0;i<n.length;i++)t(n[i]);return t}({12:[function(require,module,exports) {
function t(e){var i=new Error('Required parameter, "'+e+'" is missing.');throw"function"==typeof Error.captureStackTrace&&Error.captureStackTrace(i,t),i}var e=82.41,i=110,o=146.83,n=196,a=246.94,r=329.63,s=function(i){void 0===i&&(i={});var o=i.baseFrequency;void 0===o&&(o=e);var n=i.audioContext;void 0===n&&(n=t("audioContext")),this.audioContext=n,this.baseFrequency=o,this.playing=!1,this.scriptNode=null,this.gainNode=null,this.muteTimer=null};s.prototype.pluck=function(t){if(void 0===t&&(t=0),!(t<0)){this.playing&&this.mute(),this.scriptNode=this.audioContext.createScriptProcessor(1024,1,1);var e=this.baseFrequency*Math.pow(2,t/12),i=Math.round(this.audioContext.sampleRate/e),o=new Float32Array(i),n=0,a=!1;this.scriptNode.onaudioprocess=function(t){for(var e=t.outputBuffer,r=(t.inputBuffer.getChannelData(0),e.getChannelData(0)),s=0;s<e.length;s++){if(a){var u=(o[(n-1+i)%i]+o[(n+i)%i])/2;r[s]=u,o[n]=u}else{var c=2*Math.random()-1;r[s]=c,o[n]=c,n===i-1&&(a=!0)}n=(n+1)%i}},this.gainNode=this.audioContext.createGain(),this.gainNode.gain.value=.02,this.scriptNode.connect(this.gainNode),this.gainNode.connect(this.audioContext.destination),this.muteTimer=setTimeout(this.mute.bind(this),6e3),this.playing=!0}},s.prototype.mute=function(){this.playing&&(this.gainNode.disconnect(this.audioContext.destination),this.playing=!1,clearTimeout(this.muteTimer))};var u=function(t){void 0===t&&(t={});var u=t.audioContext;void 0===u&&(u=new AudioContext),this.audioContext=u,this.strings=[new s({audioContext:u,baseFrequency:e}),new s({audioContext:u,baseFrequency:i}),new s({audioContext:u,baseFrequency:o}),new s({audioContext:u,baseFrequency:n}),new s({audioContext:u,baseFrequency:a}),new s({audioContext:u,baseFrequency:r})]};u.prototype.strum=function(t,e){var i=this;void 0===t&&(t=[]),void 0===e&&(e=.05);var o=0;t.forEach(function(t,n){t>=0&&(setTimeout(function(){return i.strings[n].pluck(t)},Math.floor(o*e*1e3/6)),o++)})},u.prototype.pluck=function(t,e){void 0===t&&(t=6),void 0===e&&(e=0);var i=Math.abs(t-6);this.strings[i].pluck(e)},u.prototype.mute=function(){this.strings.forEach(function(t){return t.mute()})},exports.Guitar=u,exports.GuitarString=s;
},{}],11:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default={NEW_CHORD:"NEW_CHORD",PLAY_CHORD:"PLAY_CHORD",PLUCK_STRING:"PLUCK_STRING"};
},{}],10:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default={C:[-1,3,2,0,1,0],C7:[-1,3,2,0,3,0],Cm:[-1,3,5,5,4,3],Cm7:[-1,3,5,3,5,3],"C#":[-1,4,6,6,6,4],"C#7":[-1,4,6,4,6,4],"C#m":[-1,4,6,6,5,4],"C#m7":[-1,4,6,4,5,4],D:[-1,-1,0,2,3,2],D7:[-1,-1,0,2,1,2],Dm:[-1,-1,0,2,3,1],Dm7:[-1,-1,0,2,1,1],"D#":[-1,6,8,8,8,6],"D#7":[-1,6,8,6,8,6],"D#m":[-1,6,8,8,7,6],"D#m7":[-1,6,8,6,7,6],E:[0,2,2,1,0,0],E7:[0,2,0,1,3,0],Em:[0,2,2,0,0,0],Em7:[0,2,2,0,3,0],F:[1,3,3,2,1,1],F7:[1,3,1,2,1,1],Fm:[1,3,3,1,1,1],Fm7:[1,3,3,1,4,1],"F#":[2,4,4,3,2,2],"F#7":[2,4,2,3,2,2],"F#m":[2,4,4,2,2,2],"F#m7":[2,4,4,2,5,2],G:[3,2,0,0,0,3],G7:[3,2,0,0,0,1],Gm:[3,5,5,3,3,3],Gm7:[3,5,5,3,6,3],"G#":[4,6,6,5,4,4],"G#7":[4,6,4,5,4,4],"G#m":[4,6,6,4,4,4],"G#m7":[4,6,6,4,7,4],A:[-1,0,2,2,2,0],A7:[-1,0,2,0,2,0],Am:[-1,0,2,2,1,0],Am7:[-1,0,2,0,1,0],"A#":[6,8,8,7,6,6],"A#7":[6,8,6,7,6,6],"A#m":[6,8,8,6,6,6],"A#m7":[6,8,8,6,9,6],H:[-1,2,4,4,4,2],H7:[-1,2,4,2,4,2],Hm:[-1,2,4,4,3,2],Hm7:[-1,2,4,0,3,2],none:[-1,-1,-1,-1,-1,-1]};
},{}],4:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=require("./action-types"),t=a(e),r=require("./chords"),u=a(r);function a(e){return e&&e.__esModule?e:{default:e}}const d=e=>{let r=u.default.none;return a=>{a.type===t.default.NEW_CHORD?r=u.default[a.chord]||u.default.none:a.type===t.default.PLAY_CHORD?e.strum(r):a.type===t.default.PLUCK_STRING&&r&&e.pluck(a.stringNumber,r[Math.abs(a.stringNumber-6)])}};exports.default=d;
},{"./action-types":11,"./chords":10}],9:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});const e=e=>{const t=[],s=(...e)=>t.forEach(t=>t(...e));let r=!1;return{subscribe:o=>{t.push(o),r||(r=!0,e(s))}}};exports.default=e;
},{}],5:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=require("./observable"),t=r(e),o=require("./action-types"),d=r(o);function r(e){return e&&e.__esModule?e:{default:e}}const s=(0,t.default)(e=>{const t=38,o=40;document.addEventListener("keydown",r=>{if(r.keyCode===t){const t={type:d.default.PLAY_CHORD,downstroke:!1};e(t)}else if(r.keyCode===o){const t={type:d.default.PLAY_CHORD,downstroke:!0};e(t)}})});exports.default=s;
},{"./observable":9,"./action-types":11}],6:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=require("./observable"),t=d(e),r=require("./action-types"),o=d(r);function d(e){return e&&e.__esModule?e:{default:e}}const n=(0,t.default)(e=>{document.addEventListener("keydown",t=>{const r={B:6,N:5,M:4,"¼":3,"¾":2,"½":1}[String.fromCharCode(t.keyCode)];if(void 0!==r){const t={type:o.default.PLUCK_STRING,stringNumber:r};e(t)}})});exports.default=n;
},{"./observable":9,"./action-types":11}],7:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=require("./observable"),t=i(e),n=require("./chords"),r=i(n),o=require("./action-types"),d=i(o);function i(e){return e&&e.__esModule?e:{default:e}}const s=(0,t.default)(e=>{let t=[],n="none";const r=t=>{const r=u(t);if(r!==n){n=r;const t={type:d.default.NEW_CHORD,chord:n};e(t)}};document.addEventListener("keydown",e=>{t=(e=>[...new Set(e)])([...t,String.fromCharCode(e.keyCode)]),r(t)}),document.addEventListener("keyup",e=>{const n=String.fromCharCode(e.keyCode);t=t.filter(e=>e!==n),r(t)})}),u=e=>{const t=["2","3","4","5","6","7","8","9","0"],n=["Q","W","E","R","T","Y","U","I","O","P"],r=e.map(e=>t.indexOf(e)).filter(e=>e>-1),o=e.map(e=>n.indexOf(e)).filter(e=>e>-1);let d,i;if(r.length>0)d=t,i=r;else{if(!(o.length>0))return"none";d=n,i=o}const s=Math.min(...i),u=i.includes(s+1),l=i.includes(s+2);return`${{Q:"C",W:"D",E:"E",R:"F",T:"G",Y:"A",U:"H",2:"C#",3:"D#",5:"F#",6:"G#",7:"A#"}[d[s]]}${u?"m":""}${l?"7":""}`};exports.default=s;
},{"./observable":9,"./chords":10,"./action-types":11}],8:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});const e=e=>{const t=e.querySelector(".toggle-help"),o=e.querySelector(".help-text"),r=e.querySelector(".chord-info");t.addEventListener("click",()=>o.style.display="none"==(o.style.display||"none")?"block":"none");return e=>{"NEW_CHORD"===e.type&&(e=>r.innerHTML=e)(e.chord)}};exports.default=e;
},{}],3:[function(require,module,exports) {
"use strict";var e=require("ks-guitar-synth"),r=require("./guitar-player"),u=n(r),t=require("./stroke-emitter"),i=n(t),s=require("./pluck-emitter"),a=n(s),c=require("./chord-emitter"),d=n(c),l=require("./ui"),o=n(l);function n(e){return e&&e.__esModule?e:{default:e}}const b=()=>{const r=new e.Guitar,t=(0,u.default)(r);d.default.subscribe(t),i.default.subscribe(t),a.default.subscribe(t);const s=document.querySelector(".ksguitar-app"),c=(0,o.default)(s);d.default.subscribe(c)};window.onload=b;
},{"ks-guitar-synth":12,"./guitar-player":4,"./stroke-emitter":5,"./pluck-emitter":6,"./chord-emitter":7,"./ui":8}]},{},[3])